owner: agenziabergamaschi
repo: status

sites:

  # ABRE
  - name: Agenzia Bergamaschi Real Estate
    url: https://agenziabergamaschi.com
    slug: ab
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90
  - name: Agenzia Bergamaschi Real Estate (test)
    url: $URL_TEST_AB
    slug: ab-test
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90

  # ST
  - name: Spazio Tricolore
    url: https://spaziotricolore.it
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st-frontend
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90
  - name: Spazio Tricolore (test)
    url: $URL_TEST_ST
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st-test
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90
  - name: Spazio Tricolore (auth server)
    url: $URL_ST_AUTH
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st-auth
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90
  - name: Spazio Tricolore (backend)
    url: https://api.agenziabergamaschi.com/spaziotricolore/
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st-backend
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90

  # Monitor
  - name: Monitoraggio (questo sito web)
    url: https://status.agenziabergamaschi.com
    slug: monitor
    maxRetries: 5
    connectTimeout: 45
    requestTimeout: 90

status-website:
  cname: status.agenziabergamaschi.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

assignees:
  - rberga06

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
