owner: agenziabergamaschi
repo: status
sites:

  # ABRE
  - name: Agenzia Bergamaschi Real Estate
    url: https://agenziabergamaschi.com
    slug: ab

  # ST
  - name: Spazio Tricolore
    url: https://spaziotricolore.it
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st
  - name: Spazio Tricolore (backend)
    url: https://api.spaziotricolore.it
    icon: https://spaziotricolore.it/icon/icon-1024x1024.png
    slug: st-api

  # Monitor
  - name: Monitoraggio (questo sito web)
    url: https://status.agenziabergamaschi.com
    slug: monitor

status-website:
  cname: status.agenziabergamaschi.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"

assignees:
  - rberga06

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
